AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sample EC2'
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
	  ImageId: ami-0d5eff06f840b45e9
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTPS access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0